apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata: 
  name: myapp-argo-app 
  namespace: argocd
spec:
  project: default 

  source:
    repoURL: https://github.com/gandham-santhosh/helm-charts.git
    targetRevision: HEAD
    path: argo 
  destination:
    server: https://kubernetes.default.svc
    namespace: gsbapp 
  
  syncPolicy: 
    syncOptions: 
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
